Repository openstack-k8s-operators/nova-operator, pull requests merged in 2023-07, with the labels that each got.

#432 update .gitignore to ignore debug binary
  .gitignore
Labels: approved, lgtm

#433 Simplify --coverpkg argument in ginkgo
  Makefile
Labels: approved, lgtm

#436 Fix API and metadata worker counts
  templates/nova.conf
Labels: approved, lgtm

#435 Remove endpoint url and keystone service id from status
  api/v1beta1/novaapi_types.go
  api/v1beta1/novametadata_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/nova.openstack.org_novaapis.yaml
  config/crd/bases/nova.openstack.org_novametadata.yaml
  controllers/novaapi_controller.go
  controllers/novametadata_controller.go
  test/functional/nova_multicell_test.go
  test/functional/novaapi_controller_test.go
Labels: approved, lgtm

#428 Align to the validation webhook pattern
  api/v1beta1/nova_webhook.go
  api/v1beta1/novacell_webhook.go
Labels: approved, lgtm

#439 Watch RBAC resources to trigger reconcile
  controllers/nova_controller.go
Labels: approved, lgtm

#438 Add container volume mounts required for iscsi volumes
  templates/novacompute/nova_compute.json
Labels: approved, lgtm

#431 compute firewall
  controllers/novaexternalcompute_controller.go
  molecule/default/converge.yml
  molecule/default/test-data/compute-secret/firewall.yaml
  molecule/default/test-helpers/verify_firewall.yaml
  molecule/default/verify.yml
  playbooks/deploy-libvirt.yaml
  templates/firewall.goyaml
  test/functional/novaexternalcompute_controller_test.go
Labels: approved, lgtm

#440 Fix /var/lib/nova permissions in libvirt playbook
  playbooks/deploy-libvirt.yaml
Labels: approved, lgtm

#437 Add test coverage for worker count
  test/functional/nova_metadata_controller_test.go
  test/functional/novaapi_controller_test.go
Labels: approved, lgtm

#441 This change fixes binding mounting for virtlogd and qemud
  playbooks/deploy-libvirt.yaml
  templates/libvirt_virtlogd/libvirt-virtlogd.json
  templates/libvirt_virtlogd/libvirt_virtlogd.json
  templates/libvirt_virtqemud/libvirt-virtqemud.json
  templates/libvirt_virtqemud/qemu.conf
Labels: approved, lgtm

#443 Do not set transport_url for cell0 mapping
  controllers/nova_controller.go
  templates/nova.conf
  test/functional/nova_controller_test.go
Labels: approved, lgtm

#448 Update test helper references after reorg
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/functional/nova_controller_test.go
  test/functional/nova_metadata_controller_test.go
  test/functional/nova_multicell_test.go
  test/functional/nova_novncproxy_test.go
  test/functional/nova_reconfiguration_test.go
  test/functional/nova_scheduler_test.go
  test/functional/novaapi_controller_test.go
  test/functional/novacell_controller_test.go
  test/functional/novaconductor_controller_test.go
  test/functional/novaexternalcompute_controller_test.go
  test/functional/suite_test.go
Labels: approved, lgtm

#446 [EnvTest]Remove config deletion test cases
  test/functional/nova_metadata_controller_test.go
  test/functional/nova_novncproxy_test.go
  test/functional/nova_scheduler_test.go
  test/functional/novaapi_controller_test.go
  test/functional/novaconductor_controller_test.go
Labels: approved, lgtm

#451 Remove unused MessagingBusPassword
  ci/nova-operator-compute-kit/topology/base/kustomization.yaml
Labels: approved, lgtm

#455 Fix noVNC labels to be consistent for services and pods
  controllers/novametadata_controller.go
  controllers/novanovncproxy_controller.go
  test/functional/nova_metadata_controller_test.go
  test/functional/nova_novncproxy_test.go
Labels: approved, lgtm

#456 update nova/libvirt bindmounts
  templates/libvirt_virtlogd/libvirt_virtlogd.json
  templates/libvirt_virtnodedevd/libvirt_virtnodedevd.json
  templates/libvirt_virtproxyd/libvirt_virtproxyd.json
  templates/libvirt_virtqemud/libvirt_virtqemud.json
  templates/libvirt_virtsecretd/libvirt_virtsecretd.json
  templates/novacompute/nova_compute.json
Labels: approved, lgtm

#461 Configure renovate to pin k8s and controller-runtime for dev preview and pin ocp
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  renovate.json
Labels: approved, lgtm

#469 Update to use shared renovate config
  renovate.json
Labels: approved

#475 Avoid bumping own api module by renovate
  renovate.json
Labels: approved

#467 Update local ci parameters to run locally
  README.md
  ci/nova-operator-compute-kit/playbooks/deploy-openstack.yaml
  ci/nova-operator-compute-kit/playbooks/tempest.yaml
  ci/nova-operator-compute-kit/topology/base/infra.yaml
Labels: approved, lgtm, ok-to-test

#479 Propagate NetworkAttachments to AnsibleEE
  controllers/novaexternalcompute_controller.go
  test/functional/base_test.go
  test/functional/novaexternalcompute_controller_test.go
Labels: approved, lgtm
