Repository openstack-k8s-operators/nova-operator, pull requests merged in 2023-05, with the labels that each got.

#352 Fix missing template keys
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  templates/nova.conf
Labels: approved, lgtm

#355 normalize DEFAULT_IMG
  Makefile
  config/manager/kustomization.yaml
Labels: approved, lgtm, needs-ok-to-test

#335 Webhooks for default images
  Makefile
  PROJECT
  api/v1beta1/common_types.go
  api/v1beta1/nova_webhook.go
  api/v1beta1/novaapi_types.go
  api/v1beta1/novacell_webhook.go
  api/v1beta1/novaconductor_types.go
  api/v1beta1/novaexternalcompute_types.go
  api/v1beta1/novaexternalcompute_webhook.go
  api/v1beta1/novametadata_types.go
  api/v1beta1/novanovncproxy_types.go
  api/v1beta1/novascheduler_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/crd/bases/nova.openstack.org_nova.yaml
  config/crd/bases/nova.openstack.org_novaapis.yaml
  config/crd/bases/nova.openstack.org_novacells.yaml
  config/crd/bases/nova.openstack.org_novaconductors.yaml
  config/crd/bases/nova.openstack.org_novaexternalcomputes.yaml
  config/crd/bases/nova.openstack.org_novametadata.yaml
  config/crd/bases/nova.openstack.org_novanovncproxies.yaml
  config/crd/bases/nova.openstack.org_novaschedulers.yaml
  config/default/kustomization.yaml
  config/default/manager_default_images.yaml
  config/default/manager_webhook_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/manager/manager.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_service.yaml
  config/samples/nova_v1beta1_novacell0.yaml
  config/samples/nova_v1beta1_novacell1-upcall.yaml
  config/samples/nova_v1beta1_novacell2-without-upcall.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  hack/clean_local_webhook.sh
  hack/configure_local_webhook.sh
  main.go
  test/functional/nova_controller_test.go
  test/functional/suite_test.go
Labels: approved, lgtm

#353 Lib common bump test helper split
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/functional/suite_test.go
Labels: approved, lgtm

#334 Do the cell registration from the nova controller
  api/go.mod
  api/go.sum
  api/v1beta1/nova_types.go
  api/v1beta1/novaapi_types.go
  api/v1beta1/novametadata_types.go
  api/v1beta1/novascheduler_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/nova.openstack.org_nova.yaml
  config/crd/bases/nova.openstack.org_novaapis.yaml
  config/crd/bases/nova.openstack.org_novametadata.yaml
  config/crd/bases/nova.openstack.org_novaschedulers.yaml
  config/samples/nova_v1beta1_novaapi.yaml
  config/samples/nova_v1beta1_novametadata.yaml
  config/samples/nova_v1beta1_novascheduler.yaml
  controllers/common.go
  controllers/nova_controller.go
  controllers/novaapi_controller.go
  controllers/novaconductor_controller.go
  controllers/novametadata_controller.go
  controllers/novascheduler_controller.go
  go.mod
  go.sum
  pkg/nova/cellmapping.go
  pkg/nova/common.go
  pkg/nova/volumes.go
  pkg/novaapi/deployment.go
  pkg/novaconductor/dbsync.go
  pkg/novaconductor/deployment.go
  pkg/novametadata/deployment.go
  pkg/novascheduler/deployment.go
  templates/nova-manage/bin/ensure_cell_mapping.sh
  templates/nova-manage/config/nova-manage-config.json
  templates/novaconductor/bin/dbsync.sh
  test/functional/base_test.go
  test/functional/nova_controller_test.go
  test/functional/nova_metadata_controller_test.go
  test/functional/nova_multicell_test.go
  test/functional/nova_reconfiguration_test.go
  test/functional/nova_scheduler_test.go
  test/functional/novaapi_controller_test.go
  test/functional/novaconductor_controller_test.go
Labels: approved, lgtm

#357 Update cell0 DB Instance name in sample
  config/samples/nova_v1beta1_nova-multi-cell.yaml
Labels: approved, lgtm, needs-ok-to-test

#354 Lib common test helper usage
  test/functional/base_test.go
  test/functional/nova_controller_test.go
  test/functional/nova_metadata_controller_test.go
  test/functional/nova_multicell_test.go
  test/functional/nova_reconfiguration_test.go
  test/functional/nova_scheduler_test.go
  test/functional/novaapi_controller_test.go
  test/functional/novacell_controller_test.go
  test/functional/novaconductor_controller_test.go
  test/functional/novaexternalcompute_controller_test.go
  test/functional/sample_test.go
Labels: approved, lgtm

#358 [envtest]Fix copy paste issue from cell reg series
  test/functional/nova_metadata_controller_test.go
Labels: approved, lgtm

#359 [envtest]Remove unknown cellName field from template
  test/functional/base_test.go
  test/functional/nova_multicell_test.go
  test/functional/nova_reconfiguration_test.go
Labels: approved, lgtm

#323 [envtest] Factor out name handling
  test/functional/base_test.go
  test/functional/nova_controller_test.go
  test/functional/nova_metadata_controller_test.go
  test/functional/nova_multicell_test.go
  test/functional/nova_reconfiguration_test.go
  test/functional/nova_scheduler_test.go
  test/functional/novaapi_controller_test.go
  test/functional/novacell_controller_test.go
  test/functional/novaconductor_controller_test.go
  test/functional/novaexternalcompute_controller_test.go
  test/functional/sample_test.go
  test/functional/suite_test.go
Labels: approved, lgtm

#362 [envtest]Force binaries to run on ipv4 localhost
  test/functional/suite_test.go
Labels: approved, lgtm

#356 Fix panic in nova-controller if cell0 DB creation is late
  controllers/nova_controller.go
  test/functional/base_test.go
  test/functional/nova_multicell_test.go
Labels: approved, lgtm

#365 always generate the service_user config when deploying nova.
  templates/nova.conf
  test/functional/novaapi_controller_test.go
Labels: approved, lgtm

#368 Rename master to main
  .github/workflows/build-nova-operator.yaml
  README.md
Labels: approved, lgtm

#371 Use CreateConfigMap helper from lib-common
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/functional/base_test.go
  test/functional/novaexternalcompute_controller_test.go
Labels: approved, lgtm

#369 Remove manually setting internal endpoint on KeystoneAPI
  test/functional/nova_controller_test.go
  test/functional/nova_multicell_test.go
  test/functional/nova_reconfiguration_test.go
Labels: approved, lgtm

#373 Controller manager label finalization
  config/manager/manager.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_service.yaml
  config/webhook/service.yaml
Labels: approved, lgtm

#377 Add missing local webhooks
  Makefile
  hack/clean_local_webhook.sh
  hack/configure_local_webhook.sh
Labels: approved, lgtm

#381 Bump nova-api probe timeout
  pkg/novaapi/deployment.go
Labels: approved, lgtm

#382 Add basic nova scale kuttl tests
  kuttl-multicell-test.yaml
  test/kuttl/tests/multi_cell/common/cleanup_mariadb_rabbitmq.yaml
  test/kuttl/tests/multi_cell/common/mariadb_cell1/kustomization.yaml
  test/kuttl/tests/multi_cell/common/mariadb_cell1/mariadb_v1beta1_mariadb_cell1.yaml
  test/kuttl/tests/multi_cell/common/multi_cell_sample_deployment.yaml
  test/kuttl/tests/multi_cell/common/rabbitmq_cell1/rabbitmq_cell1.yaml
  test/kuttl/tests/multi_cell/multi_cell_scale/00-cleanup-nova.yaml
  test/kuttl/tests/multi_cell/multi_cell_scale/01-assert.yaml
  test/kuttl/tests/multi_cell/multi_cell_scale/01-deploy_nova.yaml
  test/kuttl/tests/multi_cell/multi_cell_scale/02-assert.yaml
  test/kuttl/tests/multi_cell/multi_cell_scale/02-scale-nova.yaml
  test/kuttl/tests/multi_cell/multi_cell_scale/03-assert.yaml
  test/kuttl/tests/multi_cell/multi_cell_scale/03-scale-down-nova.yaml
  test/kuttl/tests/multi_cell/multi_cell_scale/04-assert.yaml
  test/kuttl/tests/multi_cell/multi_cell_scale/04-scale-down-zero-nova.yaml
  test/kuttl/tests/multi_cell/multi_cell_scale/05-cleanup-nova.yaml
  test/kuttl/tests/multi_cell/multi_cell_scale/06-cleanup-mariadb-rabbitmq.yaml
Labels: approved, lgtm, ok-to-test

#383 update ceph bind mounts
  templates/libvirt_virtqemud/libvirt-virtqemud.json
  templates/libvirt_virtqemud/libvirt_virtqemud.json
  templates/novacompute/nova-compute.json
  templates/novacompute/nova_compute.json
Labels: approved, lgtm

#384 Allow skip firewall setup when starting webhooks locally
  hack/configure_local_webhook.sh
Labels: approved, lgtm

#385 [envtest]Use lib-common helper for statefulset
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/functional/base_test.go
  test/functional/nova_controller_test.go
  test/functional/nova_metadata_controller_test.go
  test/functional/nova_reconfiguration_test.go
  test/functional/nova_scheduler_test.go
  test/functional/novaapi_controller_test.go
  test/functional/novacell_controller_test.go
  test/functional/novaconductor_controller_test.go
Labels: approved, lgtm

#389 Use built-in function to evaluate ReadyCondition
  api/v1beta1/nova_types.go
  api/v1beta1/novacell_types.go
  api/v1beta1/novaexternalcompute_types.go
Labels: approved, lgtm
