Repository openstack-k8s-operators/nova-operator, pull requests merged in 2023-02, with the labels that each got.

#245 Provide additional label to identify the operator
  config/manager/manager.yaml
Labels: approved, lgtm

#246 Bump to golang 1.19 and SDK 1.26
  .github/workflows/build-nova-operator.yaml
  Dockerfile
  Makefile
  api/go.mod
  config/crd/bases/nova.openstack.org_nova.yaml
  config/crd/bases/nova.openstack.org_novaapis.yaml
  config/crd/bases/nova.openstack.org_novacells.yaml
  config/crd/bases/nova.openstack.org_novaconductors.yaml
  config/crd/bases/nova.openstack.org_novametadata.yaml
  config/crd/bases/nova.openstack.org_novanovncproxies.yaml
  config/crd/bases/nova.openstack.org_novaschedulers.yaml
  go.mod
Labels: approved, lgtm

#247 Make sure renovate runs make manifests generate
  renovate.json
Labels: approved, lgtm

#249 switch to infra-operator for rabbitmqv1
  controllers/nova_controller.go
  go.mod
  go.sum
  main.go
  test/functional/base_test.go
  test/functional/suite_test.go
Labels: approved, lgtm

#252 Update renovate config to use go 1.19
  renovate.json
Labels: approved

#242 Switch Nova default to cell separation
  api/v1beta1/nova_types.go
  config/crd/bases/nova.openstack.org_nova.yaml
  config/samples/nova_v1beta1_nova.yaml
  config/samples/nova_v1beta1_nova_only_cell0.yaml
  test/functional/sample_test.go
Labels: approved, lgtm

#258 Pass GITHUB_TOKEN to install_kustomize.sh to avoid rate-limit
  .github/workflows/build-operator-dont-publish.yaml
Labels: approved, lgtm

#261 Update pre-commit hook with bashate
  .github/create_bundle.sh
  .pre-commit-config.yaml
  templates/common/common.sh
  templates/novaconductor/bin/dbsync.sh
  templates/novaconductor/bin/init.sh
Labels: approved, lgtm

#263 Add build_root image configuration for prow
  .ci-operator.yaml
Labels: approved, lgtm, ok-to-test

#264 [renovate]Run go work sync to keep go.mod files in sync
  renovate.json
Labels: approved, lgtm

#262 Run go work synch during make gowork
  Makefile
  api/go.mod
  api/go.sum
Labels: approved, lgtm

#270 add noop zuul job to test zuul integration.
  .zuul.yaml
Labels: approved, lgtm

#248 Support attaching pods to networks using net-attach-defs and exposing api via metallb
  api/go.mod
  api/go.sum
  api/v1beta1/common_types.go
  api/v1beta1/novaapi_types.go
  api/v1beta1/novaconductor_types.go
  api/v1beta1/novametadata_types.go
  api/v1beta1/novanovncproxy_types.go
  api/v1beta1/novascheduler_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/nova.openstack.org_nova.yaml
  config/crd/bases/nova.openstack.org_novaapis.yaml
  config/crd/bases/nova.openstack.org_novacells.yaml
  config/crd/bases/nova.openstack.org_novaconductors.yaml
  config/crd/bases/nova.openstack.org_novametadata.yaml
  config/crd/bases/nova.openstack.org_novanovncproxies.yaml
  config/crd/bases/nova.openstack.org_novaschedulers.yaml
  config/rbac/role.yaml
  controllers/common.go
  controllers/nova_controller.go
  controllers/novaapi_controller.go
  controllers/novaconductor_controller.go
  controllers/novascheduler_controller.go
  go.mod
  go.sum
  main.go
  pkg/novaapi/deployment.go
  pkg/novaconductor/dbsync.go
  pkg/novaconductor/deployment.go
  pkg/novascheduler/deployment.go
  test/functional/novaapi_controller_test.go
Labels: approved, lgtm

#234 Switch to test helper more resources operations
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/functional/base_test.go
  test/functional/nova_controller_test.go
  test/functional/nova_multicell_test.go
  test/functional/nova_reconfiguration_test.go
  test/functional/novaapi_controller_test.go
Labels: approved, lgtm
