Repository openstack-k8s-operators/nova-operator, pull requests merged in 2023-01, with the labels that each got.

#206 Use the new lib-common/common/log interface
  controllers/nova_controller.go
  go.mod
  go.sum
  go.work.sum
Labels: approved, lgtm

#212 Make pre-commit.ci's gofmt happy
  api/v1beta1/conditions.go
  api/v1beta1/groupversion_info.go
  api/v1beta1/novacell_types.go
  controllers/novaconductor_controller.go
  test/functional/base_test.go
  test/functional/nova_controller_test.go
  test/functional/nova_multicell_test.go
  test/functional/nova_reconfiguration_test.go
  test/functional/novaapi_controller_test.go
  test/functional/novacell_controller_test.go
  test/functional/novaconductor_controller_test.go
Labels: approved, lgtm

#210 Revert "Use the new lib-common/common/log interface"
  controllers/nova_controller.go
  go.mod
  go.sum
  go.work.sum
Labels: approved, lgtm

#201 Bumping operator deps
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  go.work.sum
Labels: approved, lgtm

#204 Use switch when checking status enum values
  controllers/nova_controller.go
Labels: approved, lgtm

#213 Github action to avoid merging go.mod replace lines
  .github/workflows/golangci-lint.yaml
Labels: approved, lgtm

#205 Use PatchInstance from lib-common
  api/go.mod
  api/go.sum
  controllers/common.go
  controllers/nova_controller.go
  controllers/novaapi_controller.go
  controllers/novacell_controller.go
  controllers/novaconductor_controller.go
  go.mod
  go.sum
  go.work.sum
Labels: approved, lgtm

#214 Enable errorlint in golangci-lint
  .golangci.yaml
Labels: approved, lgtm

#215 Get rid of deprecated [DEFAULT] use_forwarded_for
  templates/nova.conf
Labels: approved, lgtm, ok-to-test

#218 Remove unused www_authenticate_uri option
  templates/nova.conf
Labels: approved, lgtm, ok-to-test

#219 Fix wrong option to determine cinder endpoint type
  templates/nova.conf
Labels: approved, lgtm, needs-ok-to-test

#216 Drop deprecated ovsdb_interface
  templates/nova.conf
Labels: approved, lgtm, ok-to-test

#207 Enable renovate bot to manage dep bumps
  .github/dependabot.yml
  renovate.json
Labels: approved, lgtm

#221 sync go work deps with go mod
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  go.work.sum
  test/functional/sample_test.go
Labels: approved, lgtm

#222 Fix the bundle build
  config/samples/kustomization.yaml
Labels: approved, lgtm

#211 Switch to test helper resources operations
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  go.work.sum
  test/functional/base_test.go
  test/functional/nova_controller_test.go
  test/functional/nova_multicell_test.go
  test/functional/nova_reconfiguration_test.go
  test/functional/novaapi_controller_test.go
  test/functional/novacell_controller_test.go
  test/functional/novaconductor_controller_test.go
  test/functional/sample_test.go
  test/functional/suite_test.go
Labels: approved, lgtm

#229 [CI]Remove duplications
  .github/workflows/golangci-lint.yaml
  .github/workflows/lints.yaml
Labels: approved, lgtm

#173 add suppport for the nova scheduler
  api/v1beta1/conditions.go
  api/v1beta1/nova_types.go
  api/v1beta1/novascheduler_types.go
  config/crd/bases/nova.openstack.org_nova.yaml
  config/crd/bases/nova.openstack.org_novaschedulers.yaml
  config/samples/nova_v1beta1_novascheduler.yaml
  controllers/common.go
  controllers/nova_controller.go
  controllers/novaapi_controller.go
  controllers/novaconductor_controller.go
  controllers/novascheduler_controller.go
  go.work.sum
  main.go
  pkg/novascheduler/const.go
  pkg/novascheduler/deployment.go
  templates/nova-blank.conf
  templates/novascheduler/bin/.keep
  templates/novascheduler/config/nova-scheduler-config.json
  test/functional/base_test.go
  test/functional/nova_controller_test.go
  test/functional/nova_multicell_test.go
  test/functional/nova_reconfiguration_test.go
  test/functional/nova_scheduler_test.go
  test/functional/novaapi_controller_test.go
Labels: approved, lgtm

#228 [CI] workflow for bundle and image build
  .github/workflows/build-operator-dont-publish.yaml
  Makefile
Labels: approved, lgtm

#227 Generate manifests before test run
  Makefile
Labels: approved, lgtm

#235 Remove and ignore go.work.sum
  .gitignore
  go.work.sum
Labels: approved, lgtm

#236 [envtest]Bump envtest timeout to 10 secs
  test/functional/base_test.go
Labels: approved, lgtm

#238 Ensure ./bin exists when downloading operator-sdk
  Makefile
Labels: approved, lgtm

#239 Drop paths-ignore from build-nova-operator workflow
  .github/workflows/build-nova-operator.yaml
Labels: approved, lgtm

#237 Test logging improvements
  Makefile
  test/functional/suite_test.go
Labels: approved, lgtm

#240 Remove and ignore go.work
  .gitignore
  Makefile
  go.work
Labels: approved, lgtm

#241 Fix conductor ready with 0 replicas requested
  controllers/novaconductor_controller.go
  test/functional/nova_multicell_test.go
Labels: approved, lgtm

#174 add_service_db_finalizer_logic
  controllers/nova_controller.go
  go.mod
  go.sum
  test/functional/nova_controller_test.go
Labels: approved, lgtm, ok-to-test

#244 Add a collapsed cell sample
  config/samples/nova_v1beta1_nova_collapsed_cell.yaml
  test/functional/sample_test.go
Labels: approved, lgtm
